"""
Catálogo de productos: términos de búsqueda y presentaciones de supermercado.
precio_unitario esperado: COP/kg (peso), COP/L (volumen), COP/unidad (unidad).
"""

# tipo: peso | volumen | unidad — coincide con recetas/inventory
# presentacion_*: tamaño del paquete cuando el sitio muestra precio por empaque
PRESENTACIONES = {
    "espinazo_cerdo": {"tipo": "peso"},
    "pechuga_pollo": {"tipo": "peso"},
    "muslo_pollo": {"tipo": "peso"},
    "alitas_pollo": {"tipo": "peso"},
    "menudencias_pollo": {"tipo": "peso"},
    "carne_mechar": {"tipo": "peso"},
    "bistec_res": {"tipo": "peso"},
    "filete_pescado": {"tipo": "peso"},
    "atun": {"tipo": "unidad", "unidades_por_paquete": 1},
    "huevo": {"tipo": "unidad", "unidades_por_paquete": 30},
    "jamon": {"tipo": "peso", "gramos_por_paquete": 250},
    "carne_molida": {"tipo": "peso"},
    "chicharron": {"tipo": "peso", "gramos_por_paquete": 200},
    "salchichas": {"tipo": "unidad", "unidades_por_paquete": 10},
    "salchicha": {"tipo": "unidad", "unidades_por_paquete": 1},
    "higado_res": {"tipo": "peso"},
    "pezuña_res": {"tipo": "peso"},
    "chuleta_cerdo": {"tipo": "peso"},
    "chorizo": {"tipo": "unidad", "unidades_por_paquete": 1},
    "tocineta": {"tipo": "peso", "gramos_por_paquete": 250},
    "empanadas_carne": {"tipo": "unidad", "unidades_por_paquete": 1},
    "carimañolas": {"tipo": "unidad", "unidades_por_paquete": 1},
    "queso_fresco": {"tipo": "peso", "gramos_por_paquete": 500},
    "queso_parmesano": {"tipo": "peso", "gramos_por_paquete": 200},
    "mantequilla": {"tipo": "peso", "gramos_por_paquete": 250},
    "leche": {"tipo": "volumen", "ml_por_paquete": 1000},
    "crema_leche": {"tipo": "volumen", "ml_por_paquete": 200},
    "yogurt_griego": {"tipo": "unidad", "unidades_por_paquete": 1},
    "tomate": {"tipo": "peso"},
    "cebolla": {"tipo": "peso"},
    "cebolla_larga": {"tipo": "peso"},
    "lechuga": {"tipo": "unidad", "unidades_por_paquete": 1},
    "zanahoria": {"tipo": "peso"},
    "brocoli": {"tipo": "peso"},
    "espinaca": {"tipo": "peso", "gramos_por_paquete": 250},
    "champiñones": {"tipo": "peso", "gramos_por_paquete": 250},
    "aji": {"tipo": "peso"},
    "cilantro": {"tipo": "peso", "gramos_por_paquete": 50},
    "ajo": {"tipo": "peso"},
    "pimenton": {"tipo": "peso"},
    "pepino": {"tipo": "peso"},
    "zapallo": {"tipo": "peso"},
    "arvejas": {"tipo": "peso", "gramos_por_paquete": 500},
    "aguacate": {"tipo": "unidad", "unidades_por_paquete": 1},
    "banano": {"tipo": "peso"},
    "fresas": {"tipo": "peso", "gramos_por_paquete": 250},
    "limon": {"tipo": "unidad", "unidades_por_paquete": 1},
    "arroz": {"tipo": "peso", "gramos_por_paquete": 1000},
    "lentejas": {"tipo": "peso", "gramos_por_paquete": 500},
    "frijol_negro": {"tipo": "peso", "gramos_por_paquete": 500},
    "frijol_rojo": {"tipo": "peso", "gramos_por_paquete": 500},
    "avena": {"tipo": "peso", "gramos_por_paquete": 500},
    "pan_integral": {"tipo": "peso", "gramos_por_paquete": 450},
    "arepa": {"tipo": "unidad", "unidades_por_paquete": 1},
    "tortilla_harina": {"tipo": "unidad", "unidades_por_paquete": 10},
    "cereal": {"tipo": "peso", "gramos_por_paquete": 400},
    "harina": {"tipo": "peso", "gramos_por_paquete": 1000},
    "pasta": {"tipo": "peso", "gramos_por_paquete": 500},
    "pan_hamburguesa": {"tipo": "unidad", "unidades_por_paquete": 4},
    "granola": {"tipo": "peso", "gramos_por_paquete": 400},
    "mermelada": {"tipo": "peso", "gramos_por_paquete": 250},
    "papa": {"tipo": "peso"},
    "papa_francesa": {"tipo": "peso", "gramos_por_paquete": 1000},
    "yuca": {"tipo": "peso"},
    "platano_verde": {"tipo": "peso"},
    "platano_maduro": {"tipo": "peso"},
    "mazorca": {"tipo": "unidad", "unidades_por_paquete": 1},
    "semillas_chia": {"tipo": "peso", "gramos_por_paquete": 250},
    "sal": {"tipo": "peso", "gramos_por_paquete": 500},
    "azucar": {"tipo": "peso", "gramos_por_paquete": 1000},
    "comino": {"tipo": "peso", "gramos_por_paquete": 50},
    "canela": {"tipo": "peso", "gramos_por_paquete": 50},
    "oregano": {"tipo": "peso", "gramos_por_paquete": 50},
    "miel": {"tipo": "peso", "gramos_por_paquete": 500},
    "chocolate_polvo": {"tipo": "peso", "gramos_por_paquete": 500},
    "salsa_bbq": {"tipo": "volumen", "ml_por_paquete": 250},
    "aceite": {"tipo": "volumen", "ml_por_paquete": 1000},
    "aceite_oliva": {"tipo": "volumen", "ml_por_paquete": 500},
}

PRODUCTOS_BUSQUEDA = {
    "espinazo_cerdo": "espinazo cerdo",
    "pechuga_pollo": "pechuga pollo fresca",
    "muslo_pollo": "muslo pollo",
    "alitas_pollo": "alitas pollo",
    "menudencias_pollo": "menudencias pollo",
    "carne_mechar": "carne para mechar",
    "bistec_res": "bistec res",
    "filete_pescado": "filete pescado",
    "atun": "atun en lata",
    "huevo": "huevos AA",
    "jamon": "jamon cocido",
    "carne_molida": "carne molida res",
    "chicharron": "chicharron",
    "salchichas": "salchichas",
    "salchicha": "salchicha",
    "higado_res": "higado res",
    "pezuña_res": "pezuña res",
    "chuleta_cerdo": "chuleta cerdo",
    "chorizo": "chorizo",
    "tocineta": "tocineta",
    "empanadas_carne": "empanadas carne",
    "carimañolas": "carimañolas",
    "queso_fresco": "queso campesino",
    "queso_parmesano": "queso parmesano",
    "mantequilla": "mantequilla con sal",
    "leche": "leche entera",
    "crema_leche": "crema de leche",
    "yogurt_griego": "yogurt griego",
    "tomate": "tomate chonto",
    "cebolla": "cebolla cabezona blanca",
    "cebolla_larga": "cebolla larga",
    "lechuga": "lechuga batavia",
    "zanahoria": "zanahoria fresca",
    "brocoli": "brocoli fresco",
    "espinaca": "espinaca fresca",
    "champiñones": "champiñones frescos",
    "aji": "aji dulce",
    "cilantro": "cilantro fresco",
    "ajo": "ajo fresco",
    "pimenton": "pimenton rojo",
    "pepino": "pepino fresco",
    "zapallo": "zapallo fresco",
    "arvejas": "arvejas verdes",
    "aguacate": "aguacate hass",
    "banano": "banano fresco",
    "fresas": "fresas frescas",
    "limon": "limon tahiti",
    "arroz": "arroz blanco",
    "lentejas": "lentejas secas",
    "frijol_negro": "frijol negro",
    "frijol_rojo": "frijol rojo",
    "avena": "avena en hojuelas",
    "pan_integral": "pan integral tajado",
    "arepa": "arepa blanca",
    "tortilla_harina": "tortillas de harina",
    "cereal": "cereal desayuno",
    "harina": "harina de trigo",
    "pasta": "pasta spaghetti",
    "pan_hamburguesa": "pan hamburguesa",
    "granola": "granola",
    "mermelada": "mermelada frutas",
    "papa": "papa pastusa",
    "papa_francesa": "papa francesa congelada",
    "yuca": "yuca fresca",
    "platano_verde": "platano verde",
    "platano_maduro": "platano maduro",
    "mazorca": "mazorca fresca",
    "semillas_chia": "semillas de chia",
    "sal": "sal de mesa",
    "azucar": "azucar blanca",
    "comino": "comino en polvo",
    "canela": "canela en polvo",
    "oregano": "oregano seco",
    "miel": "miel de abejas",
    "chocolate_polvo": "chocolate en polvo",
    "salsa_bbq": "salsa bbq",
    "aceite": "aceite vegetal",
    "aceite_oliva": "aceite oliva extra virgen",
}
